  - name: "Install AwesomeWM"
    hosts: localhost
    connection: local 
    tasks:
      - name: Add Alacritty repository
        become: true
        ansible.builtin.apt_repository:
          repo: ppa:aslatter/ppa

      - name: Install AwesomeWM
        become: true
        ansible.builtin.apt:
          pkg:
            -  alacritty
          update_cache: yes
      
      - name: Creates Alacritty directory
        file:
          path: ~/.config/alacritty/themes
          state: directory
          mode: 0775
          recurse: yes
      
      - name: Clone Alacritty themes
        git:
          repo: https://github.com/alacritty/alacritty-theme
          dest: ~/.config/alacritty/themes
          clone: yes
          update: yes
          depth: 1

