  - name: "Install AwesomeWM"
    hosts: localhost
    connection: local 
    tasks:
      - name: Install AwesomeWM and dependencies
        become: true
        ansible.builtin.apt:
          pkg:
            - awesome
            - rofi
            - feh
          update_cache: yes
